version : '3'
services: 
  proxy:
    image: nginx #최신 버전의 nginx
    container_name: proxy #  container 네임은 proxy
    ports:
      - "8080:80"
     #restart: "unless-stopped"   #내부에서 에러로 인해 container가 죽을 경우 restart
    depends_on:
      - placepic1
      - placepic2
  express1:
    image: dudgns3tp/placepic:node  #어느 이미지를 사용할지
    container_name: express1
    expose:
      - "3000"  # 다른 컨테이너에게 3000번 포트 open
  express2:
    image: dudgns3tp/placepic:node
    container_name: express2
    expose:
      - "3000"